import { ProductCardProps } from "../ProductCard/productcart";
export const products: ProductCardProps[] = [
  {
    id: 1,
    nameRu: "Мясная бомба",
    nameEn: "Meat Bomb",
    price: 689,
    category: "burger",
    weight: 520,
    imageAddress: "./images/meat-bomb.jpg",
  },
  {
    id: 2,
    nameRu: "Супер сырный",
    nameEn: "Super Cheesy",
    price: 639,
    category: "burger",
    weight: 512,
    imageAddress: "./images/super-cheesy.jpg",
  },
  {
    id: 3,
    nameRu: "Сытный",
    nameEn: "Hearty",
    price: 450,
    category: "burger",
    weight: 580,
    imageAddress: "./images/hearty.jpg",
  },
  {
    id: 4,
    nameRu: "Тяжелый удар",
    nameEn: "Heavy Hit",
    price: 470,
    category: "burger",
    weight: 470,
    imageAddress: "./images/heavy-hit.jpg",
  },
  {
    id: 5,
    nameRu: "Вечная классика",
    nameEn: "Eternal Classic",
    price: 450,
    category: "burger",
    weight: 450,
    imageAddress: "./images/eternal-classic.jpg",
  },
  {
    id: 6,
    nameRu: "Итальянский",
    nameEn: "Italian",
    price: 560,
    category: "burger",
    weight: 510,
    imageAddress: "./images/italian.jpg",
  },
  {
    id: 7,
    nameRu: "Начос",
    nameEn: "Nachos",
    price: 250,
    weight: 220,
    category: "snacks",
    imageAddress: "./images/nachos.jpg",
  },
  {
    id: 8,
    nameRu: "Картошка фри",
    nameEn: "French Fries",
    price: 245,
    weight: 180,
    category: "snacks",
    imageAddress: "./images/french-fries.jpg",
  },
  {
    id: 9,
    nameRu: "Луковые кольца",
    nameEn: "Onion Rings",
    price: 230,
    weight: 160,
    category: "snacks",
    imageAddress: "./images/onion-rings.jpg",
  },
  {
    id: 10,
    nameRu: "Домашний хот-дог",
    nameEn: "Homemade Hot Dog",
    price: 290,
    weight: 250,
    category: "hot-dogs",
    imageAddress: "./images/homemade-hot-dog.jpg",
  },
  {
    id: 11,
    nameRu: "Жгучий хот-дог",
    nameEn: "Spicy Hot Dog",
    price: 239,
    weight: 245,
    category: "hot-dogs",
    imageAddress: "./images/spicy-hot-dog.jpg",
  },
  {
    id: 12,
    nameRu: "Классический хот-дог",
    nameEn: "Classic Hot Dog",
    price: 220,
    weight: 215,
    category: "hot-dogs",
    imageAddress: "./images/classic-hot-dog.jpg",
  },
  {
    id: 13,
    nameRu: "Комбо-1",
    nameEn: "Combo-1",
    price: 650,
    weight: 475,
    category: "combo",
    imageAddress: "./images/combo-1.jpg",
  },
  {
    id: 14,
    nameRu: "Комбо-2",
    nameEn: "Combo-2",
    price: 600,
    weight: 560,
    category: "combo",
    imageAddress: "./images/combo-2.jpg",
  },
  {
    id: 15,
    nameRu: "Комбо-3",
    nameEn: "Combo-3",
    price: 550,
    weight: 465,
    category: "combo",
    imageAddress: "./images/combo-3.jpg",
  },
  {
    id: 16,
    nameRu: "Комбо-4",
    nameEn: "Combo-4",
    price: 680,
    weight: 720,
    category: "combo",
    imageAddress: "./images/combo-4.jpg",
  },
];

//Пицца 8
//Вок 3
//Десерт 2
//Соусы ?
